### ISSUE TITLE
Dicom support when?

### ISSUE THREAD

**Issue by awtkns** [asim-shrestha/Git-Lab-Analyzer-#1]

**Comment by asim-shrestha** [comment]
Ń̴͙è̴̩̯͙̠̘̜͍̖͔͉̦̥̠͖̊̆́͛̐͝v̶̪̰̙͉̱͙͎͔͍̪̼̘̿̔̓̋͝͠e̷̢̨̹̰͈͉̭̺̳̳͎̣̜̋̈́͛̋̒̈̕͜͠r̸̨̡̨̭͕͍̬̫̥̭͓͍͋̿̈́̿̓̂͋̒̉̋
̶̰̜̟̖̟̳̻̱̯̩͈̪̣̍̈́̆̓̊̈̀̾̀̂̊͌͘͜
